#!/usr/bin/env python3
"""
Extension Script: ${SERIES_ID} - ${SERIES_NAME}
===============================================
Reconstructs series from original subsources with live API data.

Series Information:
- Series ID: ${SERIES_ID}
- Name: ${SERIES_NAME}
- Chapter: ${CHAPTER}
- Original Period: ${ORIGINAL_PERIOD}
- Extension Period: ${EXTENSION_PERIOD}

Subsources:
${SUBSOURCE_LIST}

Generated by: Anu Extension Standard v1.1
Template Version: 1.0
"""

import sys
import json
import hashlib
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple
import pandas as pd

# Add project paths
PROJECT_ROOT = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "Technical" / "scripts"))
sys.path.insert(0, str(PROJECT_ROOT / "Technical" / "scripts" / "tools"))

# Import fetchers
try:
    from tools.unified_fetcher import UnifiedDataFetcher
    from api_config import get_api_key
    FETCHER_AVAILABLE = True
except ImportError:
    FETCHER_AVAILABLE = False
    print("[WARN] Fetcher utilities not available. API pulls disabled.")


# =============================================================================
# SERIES CONFIGURATION
# =============================================================================

SERIES_CONFIG = {
    "series_id": "${SERIES_ID}",
    "name": "${SERIES_NAME}",
    "chapter": ${CHAPTER},
    "original_period": (${ORIGINAL_START}, ${ORIGINAL_END}),
    "extension_period": (${EXTENSION_START}, ${EXTENSION_END}),
    
    # Subsources define the complete construction of this series
    "subsources": {
        # Example subsource from chopped table (historical data)
        # "${SERIES_ID}A": {
        #     "name": "Historical Statistics",
        #     "type": "historical",
        #     "api": None,
        #     "period": (1860, 1919),
        #     "file": "Inputs/ShaikhChoppedTables/${CHOPPED_FILE}",
        #     "sheet": "${SHEET_NAME}",
        #     "column": "${COLUMN_NAME}",
        #     "transform": None,
        #     "notes": "Original historical data"
        # },
        
        # Example subsource from Shaikh's original baseline
        # "${SERIES_ID}B": {
        #     "name": "Shaikh Original",
        #     "type": "shaikh_original",
        #     "api": None,
        #     "period": (1919, 2010),
        #     "file": "Outputs/ShinyApp/data/ShaikhAbsorbed/chapter_${CHAPTER}_data.csv",
        #     "column": "${COLUMN_NAME}",
        #     "transform": None,
        #     "notes": "Shaikh's baseline data through 2010"
        # },
        
        # Example subsource from FRED API
        # "${SERIES_ID}C": {
        #     "name": "FRED Industrial Production",
        #     "type": "fred",
        #     "api": "FRED:INDPRO",
        #     "period": (2011, 2025),
        #     "transform": "annual_average",
        #     "notes": "Extension via FRED API"
        # },
        
        # Example subsource from BEA API
        # "${SERIES_ID}D": {
        #     "name": "BEA Fixed Assets",
        #     "type": "bea_fixed_assets",
        #     "api": "BEA:FixedAssets:FAAt301ESI",
        #     "period": (2011, 2025),
        #     "transform": "by_industry",
        #     "industry_filter": "${INDUSTRY_CODE}",
        #     "notes": "Extension via BEA API"
        # },
    },
    
    # Splice configuration
    "splice_years": [],  # e.g., [1919, 2010]
    "splice_methods": {},  # e.g., {1919: "growth_rate", 2010: "level_match"}
    
    # Transformation chain (from DPR)
    "transformations": [
        # {"id": "T001", "operation": "load", "input": "${SERIES_ID}A", "output": "raw_historical"},
        # {"id": "T002", "operation": "annual_average", "input": "raw_historical", "output": "annual_historical"},
        # {"id": "T003", "operation": "splice", "inputs": ["annual_historical", "baseline"], "output": "combined"},
    ],
    
    # Validation bounds
    "expected_range": {
        "min": None,  # Set expected minimum value
        "max": None,  # Set expected maximum value
    },
    
    # Output configuration
    "output_file": "Outputs/ShinyApp/data/ShaikhAbsorbed/extended/${SERIES_ID}_extended.csv",
}


# =============================================================================
# SUBSOURCE LOADING FUNCTIONS
# =============================================================================

def load_chopped_table(config: Dict) -> pd.DataFrame:
    """Load data from a Shaikh chopped table Excel file."""
    file_path = PROJECT_ROOT / config["file"]
    
    if not file_path.exists():
        raise FileNotFoundError(f"Chopped table not found: {file_path}")
    
    df = pd.read_excel(
        file_path,
        sheet_name=config.get("sheet", 0),
    )
    
    # Extract relevant column
    if "column" in config:
        if config["column"] in df.columns:
            series = df[["Year", config["column"]]].copy()
            series.columns = ["year", "value"]
        else:
            raise ValueError(f"Column {config['column']} not found in {file_path}")
    else:
        series = df
    
    return series


def load_shaikh_baseline(config: Dict) -> pd.DataFrame:
    """Load data from Shaikh's baseline absorbed data."""
    file_path = PROJECT_ROOT / config["file"]
    
    if not file_path.exists():
        raise FileNotFoundError(f"Baseline file not found: {file_path}")
    
    df = pd.read_csv(file_path)
    
    if "column" in config:
        if config["column"] in df.columns:
            series = df[["year", config["column"]]].copy()
            series.columns = ["year", "value"]
        else:
            raise ValueError(f"Column {config['column']} not found")
    else:
        series = df
    
    return series


def fetch_api_data(config: Dict, fetcher: UnifiedDataFetcher) -> Tuple[pd.DataFrame, Dict]:
    """Fetch data from API and return with provenance metadata."""
    api_spec = config["api"]
    start_year, end_year = config["period"]
    
    # Fetch data
    fetch_start = datetime.now()
    df = fetcher.get_series(api_spec, start_year, end_year)
    fetch_end = datetime.now()
    
    # Generate provenance
    provenance = {
        "api_endpoint": api_spec,
        "fetch_timestamp": fetch_start.isoformat(),
        "fetch_duration_ms": (fetch_end - fetch_start).total_seconds() * 1000,
        "rows_fetched": len(df) if df is not None else 0,
        "response_hash": hashlib.sha256(str(df).encode()).hexdigest()[:16] if df is not None else None,
    }
    
    return df, provenance


def load_subsource(subsource_id: str, config: Dict, fetcher: Optional[UnifiedDataFetcher] = None) -> Tuple[pd.DataFrame, Dict]:
    """Load a subsource based on its type."""
    source_type = config.get("type", "unknown")
    provenance = {"subsource_id": subsource_id, "type": source_type}
    
    if source_type == "historical":
        df = load_chopped_table(config)
        provenance["file"] = config["file"]
        
    elif source_type == "shaikh_original":
        df = load_shaikh_baseline(config)
        provenance["file"] = config["file"]
        
    elif source_type in ["fred", "bea_nipa", "bea_fixed_assets", "bea_gdp_industry"]:
        if fetcher is None:
            raise RuntimeError("Fetcher required for API subsources")
        df, api_prov = fetch_api_data(config, fetcher)
        provenance.update(api_prov)
        
    elif source_type == "calculated":
        # Calculated subsources are derived later
        df = pd.DataFrame()
        provenance["note"] = "Calculated from other subsources"
        
    else:
        raise ValueError(f"Unknown subsource type: {source_type}")
    
    # Filter to period
    if "period" in config and not df.empty and "year" in df.columns:
        start, end = config["period"]
        df = df[(df["year"] >= start) & (df["year"] <= end)]
    
    return df, provenance


# =============================================================================
# TRANSFORMATION FUNCTIONS
# =============================================================================

def apply_transform(df: pd.DataFrame, transform: str, **kwargs) -> pd.DataFrame:
    """Apply a transformation to the data."""
    if transform is None or transform == "none":
        return df
    
    if transform == "annual_average":
        # Convert monthly/quarterly to annual average
        if "year" in df.columns:
            return df.groupby("year").mean().reset_index()
        return df
    
    if transform == "annual_value":
        # Take year-end or specific period value
        if "year" in df.columns:
            return df.groupby("year").last().reset_index()
        return df
    
    if transform == "by_industry":
        # Filter BEA data to specific industry
        industry = kwargs.get("industry_filter")
        if industry and "IndustrYDescription" in df.columns:
            df = df[df["IndustrYDescription"].str.contains(industry, case=False)]
        return df
    
    # Add more transformations as needed
    return df


def splice_series(series_list: List[pd.DataFrame], splice_years: List[int], 
                  methods: Dict[int, str]) -> pd.DataFrame:
    """Splice multiple series together at specified years."""
    if len(series_list) == 0:
        return pd.DataFrame()
    
    if len(series_list) == 1:
        return series_list[0]
    
    combined = series_list[0].copy()
    
    for i, (splice_year, next_series) in enumerate(zip(splice_years, series_list[1:])):
        method = methods.get(splice_year, "growth_rate")
        
        if method == "growth_rate":
            # Apply growth rates from new series to continue from last baseline value
            if splice_year in combined["year"].values:
                base_value = combined[combined["year"] == splice_year]["value"].iloc[0]
                next_at_splice = next_series[next_series["year"] == splice_year]["value"].iloc[0]
                ratio = base_value / next_at_splice if next_at_splice != 0 else 1
                
                extension = next_series[next_series["year"] > splice_year].copy()
                extension["value"] = extension["value"] * ratio
                combined = pd.concat([combined, extension], ignore_index=True)
        
        elif method == "level_match":
            # Direct level matching, no adjustment
            extension = next_series[next_series["year"] > splice_year].copy()
            combined = pd.concat([combined, extension], ignore_index=True)
    
    return combined.sort_values("year").reset_index(drop=True)


# =============================================================================
# VALIDATION FUNCTIONS
# =============================================================================

def validate_series(df: pd.DataFrame, config: Dict) -> Dict:
    """Validate the extended series."""
    results = {
        "timestamp": datetime.now().isoformat(),
        "checks": [],
        "overall": "PASS",
    }
    
    # Check year range
    if not df.empty and "year" in df.columns:
        actual_start = df["year"].min()
        actual_end = df["year"].max()
        expected_start = config["original_period"][0]
        expected_end = config["extension_period"][1]
        
        year_check = {
            "name": "year_range",
            "expected": f"{expected_start}-{expected_end}",
            "actual": f"{actual_start}-{actual_end}",
            "status": "PASS" if actual_start <= expected_start and actual_end >= expected_end else "WARN",
        }
        results["checks"].append(year_check)
    
    # Check value bounds
    if "expected_range" in config and config["expected_range"]["min"] is not None:
        min_val = df["value"].min() if "value" in df.columns else None
        max_val = df["value"].max() if "value" in df.columns else None
        
        bounds_check = {
            "name": "value_bounds",
            "expected_min": config["expected_range"]["min"],
            "expected_max": config["expected_range"]["max"],
            "actual_min": min_val,
            "actual_max": max_val,
            "status": "PASS",
        }
        
        if min_val is not None:
            if config["expected_range"]["min"] is not None and min_val < config["expected_range"]["min"]:
                bounds_check["status"] = "WARN"
            if config["expected_range"]["max"] is not None and max_val > config["expected_range"]["max"]:
                bounds_check["status"] = "WARN"
        
        results["checks"].append(bounds_check)
    
    # Check for missing values
    if "value" in df.columns:
        missing_count = df["value"].isna().sum()
        missing_check = {
            "name": "missing_values",
            "count": int(missing_count),
            "status": "PASS" if missing_count == 0 else "WARN",
        }
        results["checks"].append(missing_check)
    
    # Determine overall status
    if any(c["status"] == "FAIL" for c in results["checks"]):
        results["overall"] = "FAIL"
    elif any(c["status"] == "WARN" for c in results["checks"]):
        results["overall"] = "WARN"
    
    return results


# =============================================================================
# MAIN EXTENSION FUNCTION
# =============================================================================

def extend_series(config: Dict = SERIES_CONFIG, dry_run: bool = False) -> Dict:
    """
    Execute the full series extension.
    
    Returns:
        Dict with extended data, provenance, and validation results
    """
    print(f"\n{'='*70}")
    print(f"EXTENDING SERIES: {config['series_id']} - {config['name']}")
    print(f"{'='*70}")
    
    results = {
        "series_id": config["series_id"],
        "name": config["name"],
        "timestamp": datetime.now().isoformat(),
        "subsource_provenance": {},
        "data": None,
        "validation": None,
        "status": "IN_PROGRESS",
    }
    
    # Initialize fetcher if available
    fetcher = None
    if FETCHER_AVAILABLE:
        try:
            fetcher = UnifiedDataFetcher()
            print(f"  Fetcher initialized: FRED={bool(fetcher.fred.api_key)}, BEA={bool(fetcher.bea.api_key)}")
        except Exception as e:
            print(f"  [WARN] Could not initialize fetcher: {e}")
    
    # Load all subsources
    print(f"\nLoading {len(config['subsources'])} subsources...")
    subsource_data = {}
    
    for subsource_id, sub_config in config["subsources"].items():
        print(f"  Loading {subsource_id}: {sub_config.get('name', 'Unknown')}...")
        try:
            df, prov = load_subsource(subsource_id, sub_config, fetcher)
            subsource_data[subsource_id] = df
            results["subsource_provenance"][subsource_id] = prov
            print(f"    Loaded {len(df)} rows")
        except Exception as e:
            print(f"    [ERROR] Failed to load: {e}")
            results["subsource_provenance"][subsource_id] = {"error": str(e)}
    
    # Apply transformations
    print(f"\nApplying transformations...")
    for transform in config.get("transformations", []):
        print(f"  {transform.get('id', 'T???')}: {transform.get('operation', 'unknown')}")
        # Transformation logic would go here
    
    # Splice subsources
    if config.get("splice_years"):
        print(f"\nSplicing at years: {config['splice_years']}")
        series_list = [subsource_data[sid] for sid in sorted(subsource_data.keys()) 
                       if not subsource_data[sid].empty]
        combined = splice_series(
            series_list,
            config["splice_years"],
            config.get("splice_methods", {})
        )
    else:
        # Single source or already combined
        combined = pd.concat(subsource_data.values(), ignore_index=True) if subsource_data else pd.DataFrame()
    
    results["data"] = combined
    
    # Validate
    print(f"\nValidating extended series...")
    validation = validate_series(combined, config)
    results["validation"] = validation
    print(f"  Overall validation: {validation['overall']}")
    
    # Save output
    if not dry_run and not combined.empty:
        output_path = PROJECT_ROOT / config["output_file"]
        output_path.parent.mkdir(parents=True, exist_ok=True)
        combined.to_csv(output_path, index=False)
        print(f"\nSaved to: {output_path}")
        results["output_file"] = str(output_path)
    
    results["status"] = "SUCCESS" if validation["overall"] != "FAIL" else "FAILED"
    
    print(f"\n{'='*70}")
    print(f"EXTENSION COMPLETE: {results['status']}")
    print(f"{'='*70}\n")
    
    return results


# =============================================================================
# COMMAND LINE INTERFACE
# =============================================================================

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(
        description=f"Extend series {SERIES_CONFIG['series_id']}"
    )
    parser.add_argument("--dry-run", action="store_true", help="Don't save output")
    parser.add_argument("--json", action="store_true", help="Output results as JSON")
    
    args = parser.parse_args()
    
    results = extend_series(dry_run=args.dry_run)
    
    if args.json:
        # Convert DataFrame to dict for JSON output
        if results["data"] is not None:
            results["data"] = results["data"].to_dict(orient="records")
        print(json.dumps(results, indent=2, default=str))
